[package]
name = "crypto_forum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "^0.1"
json = "*"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-smile = "0.1.0"

[dependencies.ed25519-dalek]
version = "1"
