[header]
name = ""
thread_number = 0
tags = []

[[messages]]
prev_hash = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
public_key = "KJcfesnQWKeDRKeuieJ49kwvoHBTSfrDW8Ao3P8M/k0"
body = "hello"
signature = "3zbQ2rYoK0N+kOp6vAH0kbKbgIRoyjhLtjQevVW71BrRWI/mFtyZ6A2VqETepyT32q8fd15/XhgpN/tqSST8Bg"

[[messages]]
prev_hash = "F70YJmxa1O7FfH38rIO9oJaSOfh6JakaNpT91pxWVDDVfqlucMGLq1YcsP5gB5Cib2TfW3upRagdNOx7TRDIlQ"
public_key = "KJcfesnQWKeDRKeuieJ49kwvoHBTSfrDW8Ao3P8M/k0"
body = "I don't like you"
signature = "NxZJIUOECROyiq5tZpaB+n8YTONvdcJnWa1PzItJ1e/+YrSfKplITb4BCyMCBP9JSrEYhXTmhNYHgUDt8MOkDw"

[[messages]]
prev_hash = "lUogWo/yGck5iYzywKosyaRz6rpFzkRZNY0rxq5UyT+jM68DuaSarUbWRA83/9bRVW/61Fq7Izbqg9LrT0RxlA"
public_key = "/WPdRqD10IEZFJmZQLr+oo4VI5qccFV3Li8aUd0+GVw"
body = "hi"
signature = "34+KsPbbgJA7wi8cYiQ9F8v4YlgHLE5Afu9kdXBNscTxGQJmJsvqgOaetK6VDNUMcZyFuUxWZIlzThPcr9g0BQ"
